[package]
name = "service_intervals"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.11", features = ["derive"] }
csv = "1.3.0"
serde = { version = "1.0.204", features = ["derive"] }
thiserror = "1.0.63"
