//! Errors that might be enountered by the service intervals library.

use thiserror::Error;

/// Error variants for service interval operations.
#[derive(Error, Debug)]
pub enum Error {
    /// The Garmin Activity file was invalid - which likely means the format
    /// of the files generated by Garmin has changed since this program was
    /// written.
    #[error("Invalid activity file format or contents")]
    ActivityFormatError(#[source] csv::Error),

    /// The database file used by this program to persist state was invalid,
    /// which likely means it was tampered with, or is from an older or newer
    /// version of the program.
    #[error("Invalid DB file format or contents")]
    DBFormatError(#[source] anyhow::Error),

    /// An IO error was encountered when trying to interact with the filesystem.
    #[error("IO error for path: \"{file_path}\"")]
    IOError {
        /// The underlying error source.
        #[source]
        source: std::io::Error,
        /// The file or directory path upon which an IO operation was attempted.
        file_path: String,
    },

    /// An unknown error occurred.
    #[error("Unknown error")]
    Unknown,
}
